// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// {{ .Timestamp }}
package main

import (
	"runtime"
	{{ range $resource, $types := .ResourcesTypes -}}
	"github.com/aws/aws-sdk-go-v2/service/{{ $resource }}"
	{{ end -}}
)

func init() {
	// We have to generate this crawling the source code of the sdk of
	// CloudFormation or similar
	// This is a must :-(
	{{- range $resource, $types := .ResourcesTypes }}
	{{- range $type := $types }}
	typeRegistry.Set("{{ $resource }}", new({{ $resource }}.{{ $type }}))
	{{- end -}}
	{{ end }}
	runtime.GC()
}
