// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// {{ .Timestamp }}
package aws_resources

import (
	"runtime"

	{{ range .ResourcesTypes -}}
	"github.com/aws/aws-sdk-go-v2/service/{{ ToLower .Name }}"
	{{ end -}}
)

type r struct {
	resource string
	kind     string
}

var search = map[r]string{
	{{- range $index, $typ := .ResourcesTypes }}
		{{- range $typ.Resources }}
		r{resource: "{{ ToLower $typ.Name }}", kind: "{{ Clean . }}"}: "{{ GetPrefix . }}",
		{{- end }}
	{{ end }}
}

func init() {
	// We have to generate this crawling the source code of the sdk of
	// CloudFormation or similar
	// This is a must :-(
{{- range $index, $typ := .ResourcesTypes }}
	{{- range $typ.Resources }}
	typeRegistry.Set("{{ ToLower $typ.Name }}", new({{ ToLower $typ.Name }}.{{ . }}))
	{{- end -}}
	{{ end }}
	runtime.GC()
}
